# "$schema" = 'https://starship.rs/config-schema.json'
add_newline = true 

format = "$status$cmd_duration$time$directory$fill$nix_shell$git_branch$git_state$git_status\n$username$hostname$character"

[character]
success_symbol = '\$'
error_symbol = '\$'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[username]
show_always = true
format = '[$user@]($style)'
style_user = 'green'

[hostname]
ssh_only = false
aliases = {"epsilon" = "ε", "delta" = "δ"}
format = '[$hostname]($style)[$ssh_symbol](red) '
ssh_symbol = '\(ssh\)'
style = 'green'

[directory]
style = 'blue'

[time]
disabled = false
format = '[\[$time\]]($style) '

[cmd_duration]
disabled = false
min_time = 2_00
format = "Took: [$duration]($style)\n"

[status]
format = '[$symbol$status]($style) '
symbol = '\$?='
disabled = false
