# "$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

format = "$nix_shell$rust$python$lua$git_branch$git_state$git_status$fill$time\n$username$hostname$directory" 


[character] # The name of the module we are configuring is 'character'
success_symbol = '[\\$](bold green)'
error_symbol = '[\\$](bold red)'

[character.root]
success_symbol = "#"


[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[username]
show_always = true
format = '[$user@]($style)'
style_user = 'green'

[hostname]
ssh_only = false
aliases = {"epsilon" = "ε", "delta" = "δ"}
format = '[$ssh_symbol$hostname]($style):'
style = 'green'

[directory]
style = 'blue'

[time]
disabled = false
format = '[\[$time\]]($style)'
