build-home:
    home-manager --flake . build

switch-home:
    home-manager --flake . build

build-os:
    nixos-rebuild --flake . build

switch-os:
    sudo nixos-rebuild --flake . switch

update:
    nix flake update

clean:
    nix-store --gc
    sudo nix-collect-garbage -d
